---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: |
    ```ruby
    def saludar(nombre):
      "Hola " + nombre        
    end
    ```
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: |
    ```javascript
    function saludar(nombre) {
      return "Hola " + nombre;
    }
    ```
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: |
    ```python
    def saludar(nombre):
      return "Hola " + nombre 
    ```
  checked: true
name: No te entiendo nada
