---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "<code><pre>hello<br>world<br></pre></code>"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 'def doble(numero):'
  checked: false
name: No te entiendo nada
